var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "día": "d",
            "dom": "Dom",
            "lun": "Lun",
            "mar": "Mar",
            "mie": "Mie",
            "jue": "Jue",
            "vie": "Vie",
            "sab": "Sab",
            "ene": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "abr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "ago": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dic": "Dic"
        },
        "no_implemented": "No implementado",
        "to_date_view": "Click para ver la fecha actual",
        "i_undefined": "Indefinido",
        "allday_event": "Todo el día",
        "repeat_event": "Repetir Actividad",
        "time": "Fecha: ",
        "event": "Nivel - Topic: ",
/*        "location": "Ubicación",*/
				"location": "Profesor: ", 
       /* "participant": "Participante",*/
			  "participant": "Sede: ",
        "get_data_exception": "Excepción al obtener datos",
        "new_event": "Nuevo evento",
        "confirm_delete_event": "Confirma que desea Borrar esta Actividad? ",
        "confrim_delete_event_or_all": "¿Quiere repetir todas las Actividades o sólo este? \ r \ nPulse [OK] para eliminar sólo este evento, haga clic en [Cancelar] para borrar todos las actividades",
        "data_format_error": "Error de datos en formato! ",
        "invalid_title": "El título de la Actividad no puede quedar en blanco o contener ($<>)",
        "view_no_ready": "Vista no está lista",
        /*"example": "e.j., Horario, Clase, etc.",*/        
        /*"content": "Asunto",*/
        "example":"Crear / Editar Programación de Horarios.",
        "content": "",
        "create_event": "",
        "update_detail": "Crear / Editar Programación de Horario",
        "click_to_detail": "Ver Detalle",
        "i_delete": "",
        "day_plural": "Días",
        "others": "Otros",
        "item": ""
    }
});
