var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "dia": "d",
            "dom": "Dom",
            "lun": "Lun",
            "mar": "Mar",
            "mie": "Mie",
            "jue": "Jue",
            "vie": "Vie",
            "sab": "Sab",
            "ene": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "abr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "ago": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dic": "Dic"
        },
        "no_implemented": "No implementado aun",
        "to_date_view": "Click para ver la fecha actual",
        "i_undefined": "Indefinido",
        "allday_event": "Horario de todo el día",
        "repeat_event": "Repetir horario",
        "time": "Fecha Hora",
        "event": "Horario",
        "location": "Ubicacion",
        "participant": "Participante",
        "get_data_exception": "Excepción al obtener datos",
        "new_event": "Nuevo Horario",
        "confirm_delete_event": "Confirma para borrar este Horario? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Error en el formato de Datos! ",
        "invalid_title": "Digite un Titulo ($<>)",
        "view_no_ready": "Vista no está lista",
        //"example": "e.g., meeting at room 107",
        "example": "",
        "content": "Horario",
        "create_event": "",
        "update_detail": "Crear / Editar Programación",
        "click_to_detail": "Ver detalles Programación",
        "i_delete": "Borrar",
        "day_plural": "dias",
        "others": "Otros",
        "item": ""
    }
});
